nume_proiect/aplicatie1/urls.py
#vom pune url-urile secundare ale aplicatiei
from django.urls import path, include

from aplicatie1 import views

app_name = 'locations'

urlpatterns = [

    path('', views.LocationsView.as_view(), name='lista_locatii'),
    path('adaugare/', views.CreateLocationView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateLocationView.as_view(), name='modifica'),
    path('<int:pk>/delete/', views.delete_location, name='sterge'),
    path('locatii_inactive', views.LocationInactiveView.as_view(), name='locatii_inactive'),
    path('<int:pk>/activeaza/', views.activate_location, name='activeaza'),


]

nume_proiect/myapi/urls.py
from django.urls import path, include
from rest_framework import routers

from myapi import views #pt ca fac referire la fisierul de views.py

router = routers.DefaultRouter()
router.register('location', views.LocationViewSet)

urlpatterns = [
    path('', include(router.urls))

]

nume_proiect/nume_proiect/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('django.contrib.auth.urls'), {'next_page': '/n'}, name = 'login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name = 'login'),
    path('locations/', include ('aplicatie1.urls')),
    path('companies/', include ('aplicatie2.urls')),
    path('profile/', include ('userprofile.urls')),
    path('api/', include('myapi.urls')),

]

nume_proiect/aplicatie1/models.py
from django.db import models

# Create your models here.

class Locations(models.Model):

    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    active = models.BooleanField(default=1)

    def __str__(self):
        return f'{self.city} - {self.country}'

nume_proiect/aplicatie1/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from django.shortcuts import render, redirect

# Create your views here.
from aplicatie1.models import Locations


class LocationsView(LoginRequiredMixin, ListView):
    model = Locations
    template_name = 'aplicatie1/location_index.html'
    paginate_by = 5
    queryset = model.objects.filter(active=1)
    context_object_name = 'locations'

    def get_context_data(self, *args, **kwargs):
        data = super(LocationsView, self).get_context_data(*args, **kwargs)
        # data['locations'] = self.model.objects.filter(active=1)
        return data

class CreateLocationView(LoginRequiredMixin, CreateView):
    model = Locations
    # fields = '__all__
    fields = ['city', 'country']
    template_name = 'aplicatie1/location_form.html'

    def get_success_url(self):
        return reverse('locations:lista_locatii')

class UpdateLocationView(UpdateView):
    model = Locations
    fields = ['city', 'country']
    template_name = 'aplicatie1/Location_form.html'

    def get_success_url(self):
        return reverse('locations:lista_locatii')

@login_required
def delete_location(request, pk):
    Locations.objects.filter(id=pk).update(active=0)
    return redirect('locations:lista_locatii')

@login_required
def activate_location(request, pk):
    Locations.objects.filter(id=pk).update(active=1)
    return redirect('locations:lista_locatii')

class LocationInactiveView(LoginRequiredMixin, ListView):
    model = Locations
    template_name = 'aplicatie1/location_index.html'
    paginate_by = 5
    queryset = model.objects.filter(active=0)
    context_object_name = 'locations'

    def get_context_data(self, *args, **kwargs):
        data = super(LocationInactiveView, self).get_context_data(*args, **kwargs)
        # data['locations'] = self.model.objects.filter(active=0)
        return data

nume_proiect/templates/aplicatie1/location_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }} {{ field.errors }} <br>
        {% endfor %}
        <button type="submit">Salveaza</button>
    </form>
{% endblock %}

nume_proiect/templates/aplicatie1/location_index.html
{% extends 'base.html' %}
{% block content %}
<a id="idadaugare" class="btn btn-success" href="{% url 'locations:adauga' %}">Adauga locatie</a>
    <table class="table">
        <thead>
            <tr>
                <th>Index</th>
                <th>City</th>
                <th>Country</th>
                <th>Stare</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in locations %}
                <tr>
                    <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
                    <td>{{ item.city }}</td>
                    <td>{{ item.country }}</td>
                    <td>{% if item.active == 1 %}
                            <span>Activ</span>
                        {% else %}
                        <span>Inactiv</span>
                        {% endif %}
                    </td>
                    <td><a href="{% url 'locations:modifica' item.id %}" class="btn btn-success">Modifica</a>
                        {% if item.active == 1 %}
                        <a href="{% url 'locations:sterge' item.id %}" class="btn btn-danger">Sterge</a>
                    {% else %}
                        <a href="{% url 'locations:activeaza' item.id %}" class="btn btn-info">Activeaza</a>
                    {% endif %}

                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li><a class="btn" href="?page={{ page_obj.previous_page_number }}"><<</a></li>
        {% else %}
            <li class="disabled btn"><span><<</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="active btn btn-info"><span>{{ i }}<span class="sr-only">(curent)</span></span></li>
            {% else %}
                <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li><a class="btn" href="?page={{ page_obj.next_page_number }}">>></a></li>
        {% else %}
            <li class="disabled btn"><span>>></span></li>
        {% endif %}
        <span class="align-right">Showing {{ page_obj.start_index }} - {{ page_obj.end_index }} of
            {{ page_obj.paginator.count }}</span>
    </ul>
{% endif %}
{% endblock %}