nume_proiect/aplicatie2/urls.py
#vom pune url-urile secundare ale aplicatiei
from django.urls import path

from aplicatie2 import views

app_name = 'companies'

urlpatterns = [

    path('', views.CompanyView.as_view(), name='listare'),
    path('adaugare/', views.CreateCompanyView.as_view(), name='add'),
    path('<int:pk>/update/', views.UpdateCompanyView.as_view(), name='modifica'),
    path('<int:pk>/delete/', views.delete_companies, name='sterge'),
    path('companii_inactive', views.CompaniesInactiveView.as_view(), name='companii_inactive'),
    path('<int:pk>/activeaza/', views.activate_companies, name='activeaza'),

]

nume_proiect/myapi/urls.py
from django.urls import path, include
from rest_framework import routers

from myapi import views #pt ca fac referire la fisierul de views.py

router = routers.DefaultRouter()
router.register('location', views.LocationViewSet)

urlpatterns = [
    path('', include(router.urls))

]

nume_proiect/nume_proiect/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('django.contrib.auth.urls'), {'next_page': '/n'}, name = 'login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name = 'login'),
    path('locations/', include ('aplicatie1.urls')),
    path('companies/', include ('aplicatie2.urls')),
    path('profile/', include ('userprofile.urls')),
    path('api/', include('myapi.urls')),

]

nume_proiect/aplicatie2/models.py
from django.db import models
from aplicatie1.models import Locations

company_choices = (('SRL', 'S.R.L.'), ('SA', 'S.A.'))  # ca sa aleaga utilizatorul



class Companies(models.Model):
    name = models.CharField(max_length=100)
    website = models.CharField(max_length=100)
    company_type = models.CharField(max_length=10, choices=company_choices)
    active = models.BooleanField(default=1)
    location = models.ForeignKey(Locations, on_delete=models.CASCADE)
    def __str__(self):
        return f'{self.name} - {self.company_type}'

nume_proiect/aplicatie2/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from aplicatie2.models import Companies


class CompanyView(LoginRequiredMixin, ListView):
    model = Companies  #din models
    template_name = 'aplicatie2/Companies_index.html'

    def get_context_data(self, *args, **kwargs):
        data = super(CompanyView, self).get_context_data(*args, **kwargs)
        data['companies_list'] = self.model.objects.filter(active=1)
        return data


class CreateCompanyView(LoginRequiredMixin, CreateView):
    model = Companies
    fields = ['name', 'company_type', 'website', 'active']
    template_name = 'aplicatie2/Companies_form.html'

    def get_success_url(self):
        return reverse('companies:listare')


class UpdateCompanyView(LoginRequiredMixin, UpdateView):
    model = Companies
    # fields lista compurilor pe care vrem sa le editam
    fields = ['name', 'company_type', 'website', 'active']
    #template name ca la create mai sus
    template_name = 'aplicatie2/Companies_form.html'

    def get_success_url(self):
        return reverse('companies:listare')


@login_required
def delete_companies(request, pk):
    Companies.objects.filter(id=pk).update(active=0)
    return redirect('companies:listare')


@login_required
def activate_companies(request, pk):
    Companies.objects.filter(id=pk).update(active=1)
    return redirect('companies:listare')


class CompaniesInactiveView(LoginRequiredMixin, ListView):
    model = Companies
    template_name = 'aplicatie2/Companies_index.html'

    def get_context_data(self, *args, **kwargs):
        data = super(CompaniesInactiveView, self).get_context_data(*args, **kwargs)
        data['companies_list'] = self.model.objects.filter(active=0)
        return data

nume_proiect/templates/aplicatie2/Companies_index.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-success" href="{% url 'companies:add' %}">Adauga o companie</a>
    <table class="table">
        <thead>
            <tr>
                <th>Index</th>
                <th>Numele companiei</th>
                <th>Website</th>
                <th>Tipul companiei</th>
                <th>Stare</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in companies_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.website }}</td>
                    <td>{{ item.company_type }}</td>
                    <td>{% if item.active == 1 %}
                            <span>Activ</span>
                        {% else %}
                        <span>Inactiv</span>
                        {% endif %}
                    </td>
                    <td><a href="{% url 'companies:modifica' item.id %}" class="btn btn-success">Modifica</a>
                        {% if item.active == 1 %}
                        <a href="{% url 'companies:sterge' item.id %}" class="btn btn-danger">Sterge</a>
                    {% else %}
                        <a href="{% url 'companies:activeaza' item.id %}" class="btn btn-info">Activeaza</a>
                    {% endif %}

                    <td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}