nume_proiect/aplicatie1/urls.py
#vom pune url-urile secundare ale aplicatiei
from django.urls import path, include

from aplicatie1 import views

app_name = 'locations'

urlpatterns = [

    path('', views.LocationsView.as_view(), name='lista_locatii'),
    path('adaugare/', views.CreateLocationView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateLocationView.as_view(), name='modifica'),
    path('<int:pk>/delete/', views.delete_location, name='sterge'),
    path('locatii_inactive', views.LocationInactiveView.as_view(), name='locatii_inactive'),
    path('<int:pk>/activeaza/', views.activate_location, name='activeaza'),


]

nume_proiect/aplicatie2/urls.py
#vom pune url-urile secundare ale aplicatiei
from django.urls import path

from aplicatie2 import views

app_name = 'companies'

urlpatterns = [

    path('', views.CompanyView.as_view(), name='listare'),
    path('adaugare/', views.CreateCompanyView.as_view(), name='add'),
    path('<int:pk>/update/', views.UpdateCompanyView.as_view(), name='modifica'),
    path('<int:pk>/delete/', views.delete_companies, name='sterge'),
    path('companii_inactive', views.CompaniesInactiveView.as_view(), name='companii_inactive'),
    path('<int:pk>/activeaza/', views.activate_companies, name='activeaza'),

]

nume_proiect/myapi/urls.py
from django.urls import path, include
from rest_framework import routers

from myapi import views #pt ca fac referire la fisierul de views.py

router = routers.DefaultRouter()
router.register('location', views.LocationViewSet)

urlpatterns = [
    path('', include(router.urls))

]

nume_proiect/nume_proiect/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('django.contrib.auth.urls'), {'next_page': '/n'}, name = 'login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name = 'login'),
    path('locations/', include ('aplicatie1.urls')),
    path('companies/', include ('aplicatie2.urls')),
    path('profile/', include ('userprofile.urls')),
    path('api/', include('myapi.urls')),

]

nume_proiect/userprofile/urls.py
from django.urls import path

from userprofile import views

app_name = 'userprofile'

urlpatterns = [
    path('new_account/', views.CreateNewAccount.as_view(), name='utilizator_nou'),
    path('start_timesheet/', views.newtimesheet, name='start_pontaj'),
    path('stop_timesheet/', views.stoptimesheet, name='stop_pontaj'),
]

nume_proiect/templates/base.html
<html>
<head>
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav>
                    <a class="btn" href="{admin}">Admin</a>
                    {% if request.user.is_authenticated %}
                    <a class="btn" href="{% url 'locations:lista_locatii' %}">Locatii active</a>
                    <a class="btn" href="{% url 'locations:locatii_inactive' %}">Locatii inactive</a>
                    <a class="btn" href="{% url 'companies:listare' %}">Companii active</a>
                    <a class="btn" href="{% url 'companies:companii_inactive' %}">Companii inactive</a>
                    <a class="btn" href="{% url 'userprofile:utilizator_nou' %}">Adaugare utilizator</a>
                    <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
                    {% if ready_to_work is False %}
                        <a href="{% url 'userprofile:stop_pontaj' %}" class="btn btn-danger">Oprire pontaj</a>
                    {% else %}
                        <a href="{% url 'userprofile:start_pontaj' %}" class="btn btn-success">Pornire pontaj</a>
                    {% endif %}
                <span>Hi, {{ request.user.username |upper }}</span>
                {% endif %}
                </nav>
            </div>
        </div>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>