proiect_todo/aplicatie1/urls.py
from django.urls import path

from aplicatie1 import views

app_name = 'todo'

urlpatterns = [
    path('', views.TodoView.as_view(), name='lista_todo'),
    path('adaugare/', views.CreateTodoView.as_view(), name='add'),
    path('<int:pk>/update/', views.UpdateTodoView.as_view(), name='modifica'),
    path('<int:pk>/delete/', views.delete_todo, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_task, name='activate'),
    path('deleted_tasks/', views.DeletedTasksView.as_view(), name='deleted_tasks'),
    path('delete_tasks/', views.DeleteTask.as_view(), name='delete_tasks'),
    path('task_done/', views.TaskDoneView.as_view(), name='task_done'),
]

proiect_todo/proiect_todo/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('todo/', include('aplicatie1.urls')),
    path('profile/', include('userprofile.urls')),
]

proiect_todo/userprofile/urls.py
from django.urls import path

from userprofile import views

app_name = 'userprofile'

urlpatterns = [
    path('new_account/', views.CreateNewAccount.as_view(), name='utilizator_nou'),
    ]

proiect_todo/aplicatie1/models.py
from django.db import models

# Create your models here.

status_choices = (("Pending", "Pending"), ("Done", "Done"), ("Deleted", "Deleted"))

class Todo(models.Model):

    task = models.CharField(max_length=100)
    responsible = models.CharField(max_length=100)
    description = models.CharField(max_length=10000)
    task_creation_date = models.DateField()
    wished_due_date = models.DateField()
    estimated_duration = models.CharField(max_length=100)
    status = models.CharField(max_length=20, choices=status_choices, default="Pending")
    active = models.BooleanField(default=1)

    def __str__(self):
        return f'{self.task} - {self.responsible} - {self.description} - {self.task_creation_date} - ' \
               f'{self.wished_due_date} - {self.estimated_duration}'

proiect_todo/userprofile/models.py
from django.db import models

# Create your models here.

proiect_todo/userprofile/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import TextInput


class NewAccountForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username']

    def clean(self):
        field_data = self.cleaned_data
        email_value = field_data.get('email')
        username_value = field_data.get('username')
        if User.objects.filter(email=email_value).exists():
            self._errors['email'] = self.error_class(["The email already exists, please introduce an unique email"])

        if User.objects.filter(username=username_value).exists():
            self._errors['username'] = self.error_class(['The username already exists!'])

        return field_data

proiect_todo/aplicatie1/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from aplicatie1.models import Todo


class TodoView(LoginRequiredMixin, ListView):
    model = Todo
    template_name = 'aplicatie1/todo_index.html'
    paginate_by = 5
    queryset = model.objects.filter(status="Pending")
    context_object_name = 'todo'


    def get_context_data(self, *args, **kwargs):
        data = super(TodoView, self).get_context_data(*args, **kwargs)
        return data


class CreateTodoView(LoginRequiredMixin, CreateView):
    model = Todo
    fields = ['task', 'responsible', 'description', 'task_creation_date', 'wished_due_date', 'estimated_duration']
    template_name = 'aplicatie1/todo_form.html'

    def get_success_url(self):
        return reverse('todo:lista_todo')


class UpdateTodoView(LoginRequiredMixin, UpdateView):
    model = Todo
    fields = ['task', 'responsible', 'description', 'task_creation_date', 'wished_due_date', 'estimated_duration', 'status']
    template_name = 'aplicatie1/todo_form.html'

    def get_success_url(self):
        return reverse('todo:lista_todo')

@login_required
def delete_todo(request, pk):
    Todo.objects.filter(id=pk).update(active=0, status="Deleted")
    return redirect('todo:lista_todo')

@login_required
def activate_task(request, pk):
    Todo.objects.filter(id=pk).update(active=1)
    return redirect('todo:lista_todo')


class DeleteTask(LoginRequiredMixin, UpdateView):
    model = Todo
    template_name = 'aplicatie1/todo_index.html'
    paginate_by = 5
    queryset = model.objects.filter(status="Deleted")
    context_object_name = 'todo'

    def get_context_data(self, *args, **kwargs):
        data = super(DeleteTask, self).get_context_data(*args, **kwargs)
        return data


class DeletedTasksView(LoginRequiredMixin, ListView):
    model = Todo
    template_name = 'aplicatie1/todo_index.html'
    paginate_by = 5
    queryset = model.objects.filter(status="Deleted")
    context_object_name = 'todo'

    def get_context_data(self, *args, **kwargs):
        data = super(DeletedTasksView, self).get_context_data(*args, **kwargs)
        return data


class TaskDoneView(LoginRequiredMixin, ListView):
    model = Todo
    template_name = 'aplicatie1/todo_index.html'
    paginate_by = 5
    queryset = model.objects.filter(status="Done")
    context_object_name = 'todo'

    def get_context_data(self, *args, **kwargs):
        data = super(TaskDoneView, self).get_context_data(*args, **kwargs)
        return data

proiect_todo/userprofile/views.py
import random
import string
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.generic import CreateView
from django.shortcuts import render

from userprofile.forms import NewAccountForm
punctuation = '!$%?#@'


class CreateNewAccount(LoginRequiredMixin, CreateView):
    model = User
    template_name = 'aplicatie1/todo_form.html'
    form_class = NewAccountForm

    def form_valid(self, form):
        if form.is_valid() and form.errors is False:
            form.save(commit=False)
        return super(CreateNewAccount, self).form_valid(form)

    def form_invalid(self, form):
        print(form.errors)
        return super(CreateNewAccount, self).form_invalid(form)

    def get_success_url(self):

        psw = ''.join(
            random.SystemRandom().choice(string.ascii_uppercase + string.ascii_lowercase + string.digits + punctuation)
            for _ in range(8))
        if User.objects.filter(id=self.object.id).exists():
            user_instance = User.objects.get(id=self.object.id)
            user_instance.set_password(psw)
            user_instance.save()
            content = f"Credentials are: \n username: {user_instance.username} \n password: {psw}"
            msg_html = render_to_string('registration/invite_user.html', {"content_email": content})
            email = EmailMultiAlternatives(subject="User invitation", body=content, from_email='contact@todo.ro', to=[user_instance.email])
            email.attach_alternative(msg_html, 'text/html')
            email.send()
        return reverse('todo:lista_todo')

proiect_todo/templates/aplicatie1/todo_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }} {{ field.errors }} <br>
        {% endfor %}
        <button class = "btn btn-outline-primary " type ="submit">Save</button>
    </form>
{% endblock %}

proiect_todo/templates/aplicatie1/todo_index.html
{% extends 'base.html' %}
{% block content %}
    <a class="btn btn-outline-primary" href="{% url 'todo:add' %}">Add task</a>
    <table class="table">
        <thead>
            <tr>
                <th>No</th>
                <th>Task</th>
                <th>Responsible</th>
                <th>Description</th>
                <th>Task creation date</th>
                <th>Wished due date</th>
                <th>Estimated duration (h)</th>
                <th>State</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in todo %}
                <tr>
                    <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
                    <td>{{ item.task }}</td>
                    <td>{{ item.responsible }}</td>
                    <td>{{ item.description }}</td>
                    <td>{{ item.task_creation_date }}</td>
                    <td>{{ item.wished_due_date }}</td>
                    <td>{{ item.estimated_duration }}</td>
                    <td>{% if item.status == "Pending"%}
                        <span>Pending</span>
                        {% elif item.status == "Done"%}
                        <span>Done</span>
                        {% else %}
                        <span>Deleted</span>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'todo:modifica' item.id %}" class="btn btn-outline-info">Modify</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li><a class="btn" href="?page={{ page_obj.previous_page_number }}"><<</a></li>
        {% else %}
            <li class="disabled btn"><span><<</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="active btn btn-info"><span>{{ i }}<span class="sr-only">(curent)</span></span></li>
            {% else %}
                <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li><a class="btn" href="?page={{ page_obj.next_page_number }}">>></a></li>
        {% else %}
            <li class="disabled btn"><span>>></span></li>
        {% endif %}
        <span class="align-right">Showing {{ page_obj.start_index }} - {{ page_obj.end_index }} of
            {{ page_obj.paginator.count }}</span>
    </ul>
{% endif %}

{% endblock %}

proiect_todo/templates/base.html
<html>
<head>
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<!--<body style="background-image: url('https://www.off-time.ro/wp-content/uploads/2016/12/Zen.jpg');>-->
<body style="background-color:#FFFAFA">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav>
                    <a class="btn btn-outline-dark" href="/admin">Admin</a>
                    {% if request.user.is_authenticated %}
                        <a class="btn btn-outline-warning" href="{% url 'todo:lista_todo' %}">Pending tasks</a>
                        <a class="btn btn-outline-success" href="{% url 'todo:task_done' %}">Tasks done</a>
                        <a class="btn btn-outline-danger" href="{% url 'todo:deleted_tasks' %}">Deleted tasks</a>
                        <a class="btn btn-outline-info" href="{% url 'userprofile:utilizator_nou' %}">Join our team!</a>
                        <a class="btn btn-outline-dark" href="{% url 'logout' %}">Logout</a>
                    {%endif%}
                </nav>
            </div>
        </div>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>